### ISSUE TITLE
Invalid addon metadata causes spurious warning

### ISSUE THREAD

**Issue by ef4** [tildeio/simple-html-tokenizer#60]
This library contains two in-repo addons that are intended to support its development. They don't ship in the published npm package. But the package.json file refers to both of them even in the published case.

This means that if you try to build an ember app that has a transitive dependency on simple-html-tokenizer, you get a spurious warning:

```
WARNING:
WARNING: /Users/edward/hacking/css-blocks/node_modules/simple-html-tokenizer/commands:
WARNING:    Missing package directory
```

(Normally ember apps _don't_ depend on simple-html-tokenizer because it's consumed as a build step when publishing glimmer-vm, but this is coming up for [css-blocks](https://github.com/linkedin/css-blocks) because its glimmer template analyzer uses simple-html-tokenizer.)

**Comment by rwjblue** [comment]
Unfortunately, there isn't an easy way to have "dev deps" via `ember-addon` paths.  ember-engines has a similar issue and works around it via:

* adding these as dev deps with [file:](https://github.com/ember-engines/ember-engines/blob/73e54066644eedf142c4626f5c9ce724b10af822/package.json#L41-L42) relative paths
* a `prepublish` script to symlink those into `node_modules` (otherwise local development sucks since npm/yarn "vendor" them into node_modules and changes aren't live)

I think these should work here too...
